### ISSUE TITLE
main.py  中torch.save({'state_dict': model.state_dict()}, ckpt)  报错

### ISSUE THREAD

**Issue by liufei1997** [tmliang/SeG#2]
你好，请问 main.py  中torch.save({'state_dict': model.state_dict()}, ckpt) 的ckpt 是自己建立吗，代码运行总是这里报错

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    train(train_loader, test_loader, opt)
  File "main.py", line 66, in train
    torch.save({'state_dict': model.state_dict()}, ckpt)
NameError: name 'ckpt' is not defined

**Comment by tmliang** [comment]
ckpt的定义在main.py的第23行，应该没有问题

**Comment by liufei1997** [comment]
> ckpt的定义在main.py的第23行，应该没有问题

您好，main.py 的 23行是这个    for epoch in range(opt['epoch']):，感觉不是ckpt的定义啊

**Comment by tmliang** [comment]
你的代码可能被修改过了，参考<https://github.com/tmliang/SeG/blob/da144d4ae6105df76a4f1bf7fd14aac96c20edeb/main.py#L23>

**Comment by liufei1997** [comment]
好的，非常感谢
